import { RiskAssessment, ScanDiffResult } from '@/types/findings';
import { Asset } from '@/types/assets';


export interface DemoScenario {
  id: string;
  name: string;
  badge: string;
  tagline: string;
  asset: Asset;
  assessment: RiskAssessment;
  previousAssessment?: RiskAssessment;
  diffResult?: ScanDiffResult;
  rawResults: Record<string, unknown>;
}

export const DEMO_SCENARIOS: Record<string, DemoScenario> = {
  fintech_prod: {
    id: 'fintech_prod',
    name: 'Fintech Core Gateway (Prod)',
    badge: 'PCI-DSS Compliant • A+',
    tagline: 'Perimetro di produzione bancaria con crittografia end-to-end, HSTS preload e DNSSEC attivo.',
    asset: {
      id: 'asset-fintech-01',
      name: 'Fintech Core API Gateway',
      target: 'api.fintech-cloud.io',
      environment: 'production',
      criticality: 'critical',
      owner: 'SecOps Team (secops@fintech-cloud.io)',
      tags: ['PCI-DSS', 'Core-Banking', 'Production'],
      notes: 'Gateway esposto per transazioni monetarie e open banking API.',
      created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
      last_scan_score: 98,
      last_scan_grade: 'A+',
      last_scan_at: new Date().toISOString(),
    },
    assessment: {
      overallScore: 98,
      grade: 'A+',
      summary: 'Postura generale valutata con punteggio 98/100 (Grado A+). La postura di rete e sicurezza perimetrale risulta solida e conforme agli standard bancari.',
      pillars: {
        availability: { category: 'availability', score: 100, criticalCount: 0, highCount: 0, mediumCount: 0, lowCount: 0, infoCount: 3 },
        configuration: { category: 'configuration', score: 98, criticalCount: 0, highCount: 0, mediumCount: 0, lowCount: 1, infoCount: 4 },
        security: { category: 'security', score: 100, criticalCount: 0, highCount: 0, mediumCount: 0, lowCount: 0, infoCount: 5 },
      },
      findings: [
        {
          id: 'sec-tls-modern',
          category: 'configuration',
          severity: 'info',
          title: 'TLS 1.3 Strict & ALPN Attivo',
          description: 'Negoziazione TLS 1.3 con curve crittografiche moderne (X25519) e HTTP/2 + HTTP/3 QUIC.',
          evidence: 'TLSv1.3 / Cipher: TLS_AES_256_GCM_SHA384 / ALPN: h3, h2',
          confidence: 1.0,
        },
        {
          id: 'sec-hsts-preload',
          category: 'configuration',
          severity: 'info',
          title: 'HSTS Preload Attivo (RFC 6797)',
          description: 'Header Strict-Transport-Security con max-age di 2 anni e inclusione nell’elenco preload dei browser.',
          evidence: 'Strict-Transport-Security: max-age=63072000; includeSubDomains; preload',
          confidence: 1.0,
        },
        {
          id: 'sec-dmarc-reject',
          category: 'configuration',
          severity: 'info',
          title: 'DMARC Enforcement p=reject',
          description: 'Politica anti-spoofing rigorosa con report aggregati e forensi attivi.',
          evidence: 'v=DMARC1; p=reject; rua=mailto:dmarc-rua@fintech-cloud.io; ruf=mailto:dmarc-ruf@fintech-cloud.io',
          confidence: 1.0,
        },
        {
          id: 'sec-no-open-db',
          category: 'security',
          severity: 'info',
          title: 'Perimetro Firewall Blindato',
          description: 'Nessun servizio di database (MySQL, Postgres, Redis, Mongo) o porta amministrativa esposta su IP pubblico.',
          evidence: 'Porte 443 (HTTPS) e 80 (Redirect 301) uniche aperte.',
          confidence: 1.0,
        },
        {
          id: 'sec-server-banner',
          category: 'configuration',
          severity: 'low',
          title: 'Server Banner Visibile (Informational)',
          description: 'L’header Server espone la versione di Cloudflare edge.',
          evidence: 'Server: cloudflare',
          confidence: 0.9,
          remediation: {
            action: 'Mascherare l’header server nei file di configurazione reverse proxy se desiderato.',
          },
        },
      ],
      deductions: [
        {
          rule: 'Server Banner Visibile',
          points: 2,
          reason: 'Esposizione firma del server web.',
          severity: 'low',
        },
      ],
    },
    rawResults: {
      target: 'api.fintech-cloud.io',
      ttfb: { ttfb: 18, dnsTime: 4, tcpTime: 8, tlsTime: 6 },
      ssl: { valid: true, daysRemaining: 180, issuer: 'DigiCert Global Root G2', protocol: 'TLSv1.3' },
      ports: { openPorts: [443] },
    },
  },

  ecommerce_drift: {
    id: 'ecommerce_drift',
    name: 'E-Commerce Monolith (Incident Drift)',
    badge: '🚨 Drift Incident • Score Crollo da 95 ad 32 (Grado F)',
    tagline: 'Simulazione di incidente post-deploy: porta Redis 6379 aperta su IP pubblico e file .env leakato.',
    asset: {
      id: 'asset-ecom-02',
      name: 'Global Storefront & API',
      target: 'shop.fashion-global.com',
      environment: 'production',
      criticality: 'critical',
      owner: 'DevOps / Release Team (devops@fashion-global.com)',
      tags: ['E-Commerce', 'Production', 'Drift-Alert'],
      notes: 'Piattaforma e-commerce principale con cataloghi e carrello ordini.',
      created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
      last_scan_score: 32,
      last_scan_grade: 'F',
      last_scan_at: new Date().toISOString(),
    },
    assessment: {
      overallScore: 32,
      grade: 'F',
      summary: 'Postura compromessa: punteggio 32/100 (Grado F). Rilevate 2 vulnerabilità CRITICHE e 1 ad alto rischio introdotte dopo l’ultimo rilascio applicativo.',
      pillars: {
        availability: { category: 'availability', score: 65, criticalCount: 0, highCount: 0, mediumCount: 1, lowCount: 0, infoCount: 1 },
        configuration: { category: 'configuration', score: 55, criticalCount: 0, highCount: 1, mediumCount: 1, lowCount: 0, infoCount: 2 },
        security: { category: 'security', score: 20, criticalCount: 2, highCount: 0, mediumCount: 1, lowCount: 0, infoCount: 1 },
      },
      findings: [
        {
          id: 'sec-port-exposed-6379',
          category: 'security',
          severity: 'critical',
          title: 'Porta Critica Esposta: 6379 (Redis In-Memory Cache)',
          description: 'Il database Redis risponde direttamente su interfaccia pubblica senza autenticazione o firewall attivo.',
          evidence: 'TCP Socket 6379 aperto su IP pubblico 198.51.100.42.',
          impact: 'Possibilità di dump completo delle sessioni utente, chiavi API o remote code execution via Redis command injection.',
          confidence: 0.99,
          remediation: {
            action: 'Chiudere immediatamente la porta 6379 tramite firewall (UFW/Security Group) e forzare il bind su 127.0.0.1 nel file redis.conf.',
            codeSnippet: 'sudo ufw deny 6379/tcp\n# Nel file /etc/redis/redis.conf:\nbind 127.0.0.1 ::1\nprotected-mode yes',
            technicalReference: 'CIS Redis Benchmark 1.1',
          },
        },
        {
          id: 'vuln-file-_env',
          category: 'security',
          severity: 'critical',
          title: 'File Sensibile Esposto: /.env (Variabili d’Ambiente)',
          description: 'Il file .env è pubblicamente scaricabile senza autenticazione dal web server.',
          evidence: 'HTTP 200 OK su https://shop.fashion-global.com/.env (Dimensione: 1.4KB). Rilevate stringhe DB_PASSWORD e STRIPE_SECRET_KEY.',
          impact: 'Esposizione immediata di segreti applicativi, password del database di produzione e chiavi di pagamento.',
          confidence: 0.99,
          remediation: {
            action: 'Rimuovere immediatamente il file dalla web root e inserire blocco esplicito nella configurazione NGINX.',
            codeSnippet: 'location ~ /\\.env {\n    deny all;\n    return 404;\n}',
            technicalReference: 'OWASP Top 10 A01:2021',
          },
        },
        {
          id: 'sec-hsts-missing',
          category: 'configuration',
          severity: 'high',
          title: 'Header HSTS Rimosso Accidentalmente',
          description: 'L’header Strict-Transport-Security (HSTS) non viene più inviato nella risposta HTTP.',
          evidence: 'Header HSTS non rilevato (era presente nella scansione precedente).',
          impact: 'Esposizione a potenziali attacchi SSL-Stripping.',
          confidence: 0.98,
          remediation: {
            action: 'Ripristinare la direttiva HSTS nel blocco server HTTPS di Nginx/Cloudflare.',
            codeSnippet: 'add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;',
          },
        },
        {
          id: 'avail-latency-high',
          category: 'availability',
          severity: 'medium',
          title: 'Degrado Severo del Tempo di Risposta (TTFB: 680ms)',
          description: 'Il TTFB è aumentato da 45ms a 680ms a seguito del sovraccarico o della misconfigurazione del caching edge.',
          evidence: 'TTFB rilevato: 680ms (+635ms rispetto alla baseline precedente).',
          confidence: 0.92,
        },
      ],
      deductions: [
        { rule: 'Porta Redis 6379 Esposta', points: 25, reason: 'Database cache accessibile pubblicamente.', severity: 'critical' },
        { rule: 'File .env Esposto', points: 25, reason: 'Leak di credenziali di produzione.', severity: 'critical' },
        { rule: 'HSTS Mancante', points: 15, reason: 'Protezione HTTPS forzata assente.', severity: 'high' },
        { rule: 'Latenza TTFB Elevata', points: 7, reason: 'Degrado prestazionale oltre soglia.', severity: 'medium' },
      ],
    },
    previousAssessment: {
      overallScore: 95,
      grade: 'A',
      summary: 'Postura precedente eccellente prima della release applicativa.',
      pillars: {
        availability: { category: 'availability', score: 98, criticalCount: 0, highCount: 0, mediumCount: 0, lowCount: 0, infoCount: 2 },
        configuration: { category: 'configuration', score: 95, criticalCount: 0, highCount: 0, mediumCount: 0, lowCount: 1, infoCount: 3 },
        security: { category: 'security', score: 98, criticalCount: 0, highCount: 0, mediumCount: 0, lowCount: 0, infoCount: 4 },
      },
      findings: [],
      deductions: [],
    },
    diffResult: {
      target: 'shop.fashion-global.com',
      previousTimestamp: new Date(Date.now() - 86400000).toISOString(),
      currentTimestamp: new Date().toISOString(),
      previousScore: 95,
      currentScore: 32,
      scoreDelta: -63,
      previousGrade: 'A',
      currentGrade: 'F',
      changes: [
        {
          id: 'drift-port-6379',
          category: 'security',
          changeType: 'added',
          title: 'NUOVA PORTA CRITICA APERTA: 6379 (Redis)',
          currentEvidence: 'Socket TCP 6379 aperto (Ieri: CHIUSA)',
          severity: 'critical',
          description: 'La porta Redis è stata esposta pubblicamente su internet a seguito di una modifica alle regole firewall.',
        },
        {
          id: 'drift-file-env',
          category: 'security',
          changeType: 'added',
          title: 'NUOVO FILE SENSIBILE ESPOSTO: /.env',
          currentEvidence: 'HTTP 200 OK (Ieri: HTTP 404 Not Found)',
          severity: 'critical',
          description: 'Un file .env contenente credenziali del database è stato copiato nella web root durante il deploy.',
        },
        {
          id: 'drift-hsts-removed',
          category: 'configuration',
          changeType: 'degraded',
          title: 'HEADER DI SICUREZZA RIMOSSO: HSTS',
          previousEvidence: 'Strict-Transport-Security: max-age=31536000',
          currentEvidence: 'Header non presente',
          severity: 'high',
          description: 'L’header Strict-Transport-Security è stato eliminato dalla configurazione del web server.',
        },
        {
          id: 'drift-ttfb-degraded',
          category: 'availability',
          changeType: 'degraded',
          title: 'DEGRADO LATENZA SERVER (TTFB)',
          previousEvidence: '45 ms',
          currentEvidence: '680 ms (+635 ms)',
          severity: 'medium',
          description: 'Il tempo di risposta al primo byte è aumentato sensibilmente.',
        },
      ],
      summary: {
        newVulnerabilities: 2,
        resolvedVulnerabilities: 0,
        configDrifts: 2,
        latencyDeltaMs: 635,
      },
    },
    rawResults: {
      target: 'shop.fashion-global.com',
      ttfb: { ttfb: 680 },
      ports: { openPorts: [80, 443, 6379, 8080] },
      files: [{ exposed: true, path: '/.env', status: 200, size: 1420 }],
    },
  },

  staging_k8s: {
    id: 'staging_k8s',
    name: 'Staging Kubernetes Cluster (Stage)',
    badge: 'Certificato in Scadenza (3 gg) • Grado C',
    tagline: 'Ambiente di collaudo con certificato SSL Let’s Encrypt in scadenza e policy email permissiva.',
    asset: {
      id: 'asset-stage-03',
      name: 'K8s Staging Ingress',
      target: 'k8s-stage.internal-dev.net',
      environment: 'staging',
      criticality: 'medium',
      owner: 'QA & Backend Team (qa-team@internal-dev.net)',
      tags: ['Staging', 'Kubernetes', 'Testing'],
      notes: 'Cluster di pre-rilascio per test funzionali.',
      created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
      last_scan_score: 64,
      last_scan_grade: 'C',
      last_scan_at: new Date().toISOString(),
    },
    assessment: {
      overallScore: 64,
      grade: 'C',
      summary: 'Postura di staging discreta: punteggio 64/100 (Grado C). Richiesto rinnovo certificato SSL e revisione porta SSH esposta.',
      pillars: {
        availability: { category: 'availability', score: 85, criticalCount: 0, highCount: 0, mediumCount: 0, lowCount: 1, infoCount: 2 },
        configuration: { category: 'configuration', score: 50, criticalCount: 0, highCount: 1, mediumCount: 1, lowCount: 0, infoCount: 1 },
        security: { category: 'security', score: 70, criticalCount: 0, highCount: 0, mediumCount: 1, lowCount: 1, infoCount: 2 },
      },
      findings: [
        {
          id: 'sec-ssl-expiry',
          category: 'configuration',
          severity: 'high',
          title: 'Certificato SSL/TLS in Scadenza (3 giorni)',
          description: 'Il certificato crittografico scadrà tra 3 giorni; se non rinnovato, i browser bloccheranno gli accessi.',
          evidence: 'Valido fino al: 30 Agosto 2026 (Giorni rimanenti: 3)',
          impact: 'Possibile interruzione totale dell’ambiente di staging per scadenza certificato.',
          confidence: 0.99,
          remediation: {
            action: 'Verificare il funzionamento del pod cert-manager in Kubernetes ed eseguire il rinnovo ACME.',
            codeSnippet: 'kubectl get certificaterequests -n ingress-nginx\ncmctl renew staging-ingress-cert',
          },
        },
        {
          id: 'sec-dmarc-weak',
          category: 'configuration',
          severity: 'medium',
          title: 'Policy DMARC in Modalità Monitoraggio (p=none)',
          description: 'Il record DMARC è impostato su p=none, non bloccando le email contraffatte.',
          evidence: 'v=DMARC1; p=none; sp=none; rua=mailto:dmarc@internal-dev.net',
          confidence: 0.95,
        },
        {
          id: 'sec-port-ssh-exposed',
          category: 'security',
          severity: 'medium',
          title: 'Porta SSH 22 Esposta Pubblicamente',
          description: 'La porta di amministrazione SSH del nodo master è aperta su internet.',
          evidence: 'Socket TCP 22 aperto su IP pubblico.',
          confidence: 0.95,
          remediation: {
            action: 'Limitare l’accesso SSH alla sola VPN aziendale o IP dell’ufficio.',
          },
        },
      ],
      deductions: [
        { rule: 'Certificato SSL in Scadenza', points: 15, reason: 'Scadenza imminente (3 giorni)', severity: 'high' },
        { rule: 'Policy DMARC Debole', points: 7, reason: 'Policy p=none', severity: 'medium' },
        { rule: 'Porta SSH 22 Esposta', points: 7, reason: 'Gestione remota accessibile da internet', severity: 'medium' },
      ],
    },
    rawResults: {
      target: 'k8s-stage.internal-dev.net',
      ssl: { valid: true, daysRemaining: 3, issuer: "Let's Encrypt Authority X3" },
      ports: { openPorts: [22, 80, 443] },
    },
  },
};
