import { RiskAssessment, ScanDiffResult } from '@/types/findings';
import { Asset } from '@/types/assets';


export interface DemoScenario {
  id: string;
  name: string;
  badge: string;
  tagline: string;
  asset: Asset;
  assessment: RiskAssessment;
  previousAssessment?: RiskAssessment;
  diffResult?: ScanDiffResult;
  rawResults: Record<string, unknown>;
}

export const DEMO_SCENARIOS: Record<string, DemoScenario> = {
  fintech_prod: {
    id: 'fintech_prod',
    name: 'Fintech Core Gateway (Prod)',
    badge: 'PCI-DSS Compliant • A+',
    tagline: 'Perimetro di produzione bancaria con crittografia end-to-end, HSTS preload e DNSSEC attivo.',
    asset: {
      id: 'asset-fintech-01',
      name: 'Fintech Core API Gateway',
      target: 'api.fintech-cloud.io',
      environment: 'production',
      criticality: 'critical',
      owner: 'SecOps Team (secops@fintech-cloud.io)',
      tags: ['PCI-DSS', 'Core-Banking', 'Production'],
      notes: 'Gateway esposto per transazioni monetarie e open banking API.',
      created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
      last_scan_score: 98,
      last_scan_grade: 'A+',
      last_scan_at: new Date().toISOString(),
    },
    assessment: {
      overallScore: 98,
      grade: 'A+',
      summary: 'Postura generale valutata con punteggio 98/100 (Grado A+). La postura di rete e sicurezza perimetrale risulta solida e conforme agli standard bancari PCI-DSS.',
      breakdown: {
        exposureScore: 100,
        postureScore: 98,
        operationalScore: 96,
        formulaExplanation: 'Punteggio Finale (98) = Exposure [100] × 50% + Posture [98] × 30% + Operational [96] × 20%',
      },
      pillars: {
        availability: { category: 'availability', score: 96, criticalCount: 0, highCount: 0, mediumCount: 0, lowCount: 0, infoCount: 3 },
        configuration: { category: 'configuration', score: 98, criticalCount: 0, highCount: 0, mediumCount: 0, lowCount: 1, infoCount: 4 },
        security: { category: 'security', score: 100, criticalCount: 0, highCount: 0, mediumCount: 0, lowCount: 0, infoCount: 5 },
      },
      findings: [
        {
          id: 'sec-tls-modern',
          category: 'configuration',
          severity: 'info',
          status: 'confirmed',
          title: 'TLS 1.3 Strict & ALPN Attivo',
          description: 'Negoziazione TLS 1.3 con curve crittografiche moderne (X25519) e HTTP/2 + HTTP/3 QUIC.',
          evidence: 'TLSv1.3 / Cipher: TLS_AES_256_GCM_SHA384 / ALPN: h3, h2',
          confidence: 1.0,
          technicalEvidence: {
            host: 'api.fintech-cloud.io',
            port: 443,
            protocol: 'TCP/TLS',
            engine: 'TLS Crittografia & ALPN Inspector',
            rawEvidence: 'Cipher Suite: TLS_AES_256_GCM_SHA384 (0x1302)\nALPN Protocoll: h3, h2\nCurve: X25519 (253 bits)',
            confidencePercentage: 100,
            firstSeen: '2026-08-01 10:00:00 UTC',
            lastVerified: '2026-08-27 20:00:00 UTC',
            resolvedIp: '104.21.58.112',
          },
        },
        {
          id: 'sec-hsts-preload',
          category: 'configuration',
          severity: 'info',
          status: 'confirmed',
          title: 'HSTS Preload Attivo (RFC 6797)',
          description: 'Header Strict-Transport-Security con max-age di 2 anni e inclusione nell’elenco preload dei browser.',
          evidence: 'Strict-Transport-Security: max-age=63072000; includeSubDomains; preload',
          confidence: 1.0,
          technicalEvidence: {
            host: 'api.fintech-cloud.io',
            port: 443,
            engine: 'HTTP Header Security Auditor',
            rawEvidence: 'HTTP/2 200 OK\nstrict-transport-security: max-age=63072000; includeSubDomains; preload',
            confidencePercentage: 99,
            firstSeen: '2026-08-01 10:00:00 UTC',
            lastVerified: '2026-08-27 20:00:00 UTC',
          },
        },
        {
          id: 'sec-dmarc-reject',
          category: 'configuration',
          severity: 'info',
          status: 'confirmed',
          title: 'DMARC Enforcement p=reject',
          description: 'Politica anti-spoofing rigorosa con report aggregati e forensi attivi.',
          evidence: 'v=DMARC1; p=reject; rua=mailto:dmarc-rua@fintech-cloud.io; ruf=mailto:dmarc-ruf@fintech-cloud.io',
          confidence: 1.0,
          technicalEvidence: {
            host: 'api.fintech-cloud.io',
            engine: 'DNS TXT & SPF/DKIM/DMARC Auditor',
            rawEvidence: '_dmarc.fintech-cloud.io TXT "v=DMARC1; p=reject; sp=reject; pct=100; rua=mailto:dmarc-rua@fintech-cloud.io"',
            confidencePercentage: 100,
            firstSeen: '2026-08-01 10:00:00 UTC',
            lastVerified: '2026-08-27 20:00:00 UTC',
          },
        },
        {
          id: 'sec-no-open-db',
          category: 'security',
          severity: 'info',
          status: 'confirmed',
          title: 'Perimetro Firewall Blindato',
          description: 'Nessun servizio di database (MySQL, Postgres, Redis, Mongo) o porta amministrativa esposta su IP pubblico.',
          evidence: 'Porte 443 (HTTPS) e 80 (Redirect 301) uniche aperte.',
          confidence: 1.0,
          technicalEvidence: {
            host: 'api.fintech-cloud.io',
            engine: 'TCP Port Scanner Pro (1000 Ports)',
            rawEvidence: 'Scan result: 443/open/https, 80/open/http (redirect 301). Tutte le altre porte chiuse/filtrate con DROP.',
            confidencePercentage: 99,
            firstSeen: '2026-08-01 10:00:00 UTC',
            lastVerified: '2026-08-27 20:00:00 UTC',
            resolvedIp: '104.21.58.112',
          },
        },
        {
          id: 'sec-server-banner',
          category: 'configuration',
          severity: 'low',
          status: 'open',
          title: 'Server Banner Visibile (Informational)',
          description: 'L’header Server espone la versione di Cloudflare edge.',
          evidence: 'Server: cloudflare',
          confidence: 0.9,
          technicalEvidence: {
            host: 'api.fintech-cloud.io',
            port: 443,
            engine: 'HTTP Header Security Auditor',
            rawEvidence: 'HTTP/2 200 OK\nserver: cloudflare\ncf-ray: 8b1f2026ae899-IAD',
            confidencePercentage: 95,
            firstSeen: '2026-08-15 14:00:00 UTC',
            lastVerified: '2026-08-27 20:00:00 UTC',
          },
          remediation: {
            action: 'Mascherare l’header server nei file di configurazione reverse proxy se desiderato.',
            codeSnippet: 'proxy_hide_header Server;',
            structured: {
              problem: 'L’header Server espone informazioni sulla tecnologia sottostante.',
              risk: 'Raccolta passiva di informazioni (Footprinting). Rischio basso.',
              immediateActions: ['Aggiungere `proxy_hide_header Server;` nel reverse proxy Nginx o Cloudflare Transform Rules.'],
              verification: 'Eseguire `curl -I https://api.fintech-cloud.io` e verificare l’assenza del campo server.',
            },
          },
        },
      ],
      deductions: [
        {
          findingId: 'sec-server-banner',
          rule: 'Server Banner Visibile',
          points: 2,
          reason: 'Esposizione firma del server web.',
          severity: 'low',
        },
      ],
    },
    rawResults: {
      target: 'api.fintech-cloud.io',
      ttfb: { ttfb: 18, dnsTime: 4, tcpTime: 8, tlsTime: 6 },
      ssl: { valid: true, daysRemaining: 180, issuer: 'DigiCert Global Root G2', protocol: 'TLSv1.3' },
      ports: { openPorts: [443] },
    },
  },

  ecommerce_drift: {
    id: 'ecommerce_drift',
    name: 'E-Commerce Monolith (Incident Drift)',
    badge: '🚨 Drift Incident • Score Crollo da 95 ad 28 (Grado F)',
    tagline: 'Simulazione di incidente post-deploy: porta Redis 6379 aperta su IP pubblico e file .env leakato.',
    asset: {
      id: 'asset-ecom-02',
      name: 'Global Storefront & API',
      target: 'shop.fashion-global.com',
      environment: 'production',
      criticality: 'critical',
      owner: 'DevOps / Release Team (devops@fashion-global.com)',
      tags: ['E-Commerce', 'Production', 'Drift-Alert'],
      notes: 'Piattaforma e-commerce principale con cataloghi e carrello ordini.',
      created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
      last_scan_score: 28,
      last_scan_grade: 'F',
      last_scan_at: new Date().toISOString(),
    },
    assessment: {
      overallScore: 28,
      grade: 'F',
      summary: 'Postura compromessa: punteggio 28/100 (Grado F). Rilevate 2 vulnerabilità CRITICHE introdotte dopo l’ultimo rilascio applicativo (porta Redis e file .env).',
      breakdown: {
        exposureScore: 15,
        postureScore: 35,
        operationalScore: 50,
        formulaExplanation: 'Punteggio Finale (28) = Exposure [15] × 50% + Posture [35] × 30% + Operational [50] × 20%',
      },
      pillars: {
        availability: { category: 'availability', score: 50, criticalCount: 0, highCount: 0, mediumCount: 1, lowCount: 0, infoCount: 1 },
        configuration: { category: 'configuration', score: 35, criticalCount: 0, highCount: 1, mediumCount: 1, lowCount: 0, infoCount: 2 },
        security: { category: 'security', score: 15, criticalCount: 2, highCount: 0, mediumCount: 1, lowCount: 0, infoCount: 1 },
      },
      findings: [
        {
          id: 'sec-port-exposed-6379',
          category: 'security',
          severity: 'critical',
          status: 'open',
          title: 'Porta Critica Esposta: 6379 (Redis In-Memory Cache)',
          description: 'Il database Redis risponde direttamente su interfaccia pubblica senza autenticazione o firewall attivo.',
          evidence: 'TCP Socket 6379 aperto su IP pubblico 198.51.100.42.',
          impact: 'Possibilità di dump completo delle sessioni utente, chiavi API o remote code execution via Redis command injection.',
          confidence: 0.99,
          technicalEvidence: {
            host: 'shop.fashion-global.com',
            port: 6379,
            protocol: 'TCP',
            engine: 'Port Scanner Pro (Socket Probe)',
            rawEvidence: 'Connected to 198.51.100.42:6379 (SYN/ACK accepted)\nPayload probe: PING\nResponse: +PONG (Unauthenticated Redis 7.2.4)',
            confidencePercentage: 99,
            firstSeen: '2026-08-27 18:30:00 UTC (Post-Deploy #148)',
            lastVerified: '2026-08-27 20:15:00 UTC',
            resolvedIp: '198.51.100.42',
          },
          remediation: {
            action: 'Limitare il binding di Redis a 127.0.0.1 nel file /etc/redis/redis.conf e abilitare il firewall UFW.',
            codeSnippet: 'sudo ufw deny 6379/tcp\nsudo sed -i "s/bind 0.0.0.0/bind 127.0.0.1/" /etc/redis/redis.conf\nsudo systemctl restart redis',
            structured: {
              problem: 'Redis In-Memory Cache è accessibile da Internet sulla porta 6379/TCP senza autenticazione.',
              risk: 'Dump non autorizzato delle sessioni carrello, token di autenticazione e rischio RCE.',
              immediateActions: [
                '1. Bloccare immediatamente la porta 6379 con `sudo ufw deny 6379/tcp`.',
                '2. Modificare il file `/etc/redis/redis.conf` impostando `bind 127.0.0.1 ::1`.',
                '3. Impostare una password forte (`requirepass <STRONG_KEY>`).',
                '4. Riavviare il servizio: `sudo systemctl restart redis-server`.',
              ],
              verification: 'Eseguire `nc -zv -w 3 shop.fashion-global.com 6379` e confermare lo stato Connection Refused o Timed Out.',
            },
          },
        },
        {
          id: 'sec-file-env-exposed',
          category: 'security',
          severity: 'critical',
          status: 'open',
          title: 'File di Configurazione Sensibile Esposto (.env)',
          description: 'Il file .env nella root del web server è pubblicamente scaricabile tramite richiesta HTTP GET.',
          evidence: 'HTTP 200 OK con contenuto text/plain contenente DB_PASSWORD e JWT_SECRET.',
          impact: 'Compromissione totale dell’infrastruttura, accesso al database di produzione e forgiatura di token di sessione.',
          confidence: 0.98,
          technicalEvidence: {
            host: 'shop.fashion-global.com',
            port: 443,
            protocol: 'HTTPS',
            engine: 'Sensitive File Leak Scanner',
            rawEvidence: 'GET /.env HTTP/1.1\nHost: shop.fashion-global.com\nHTTP/1.1 200 OK\nContent-Type: text/plain\nPayload preview: DB_CONNECTION=mysql\nDB_HOST=127.0.0.1\nDB_DATABASE=shop_prod\nDB_PASSWORD=***REDACTED***',
            confidencePercentage: 98,
            firstSeen: '2026-08-27 18:30:00 UTC (Post-Deploy #148)',
            lastVerified: '2026-08-27 20:15:00 UTC',
            httpStatus: 200,
            resolvedIp: '198.51.100.42',
          },
          remediation: {
            action: 'Aggiungere una regola di blocco globale nel file di configurazione del web server e ruotare tutte le credenziali.',
            codeSnippet: 'location ~ /\\.(env|git) {\n    deny all;\n    return 404;\n}',
            structured: {
              problem: 'File delle variabili d’ambiente `.env` scaricabile direttamente via HTTP/S.',
              risk: 'Esfiltrazione di password del database MySQL, chiavi Stripe e segreti JWT.',
              immediateActions: [
                '1. Configurare Nginx per negare l’accesso ai file che iniziano con un punto (`location ~ /\\. { deny all; }`).',
                '2. Riavviare il server web: `sudo nginx -t && sudo systemctl reload nginx`.',
                '3. Ruotare TUTTE le chiavi del database e i token API presenti nel file `.env`.',
              ],
              verification: 'Eseguire `curl -I https://shop.fashion-global.com/.env` e verificare che restituisca HTTP 404 o 403.',
            },
          },
        },
        {
          id: 'sec-hsts-removed',
          category: 'configuration',
          severity: 'high',
          status: 'open',
          title: 'Header HSTS Rimosso nella Release',
          description: 'L’header Strict-Transport-Security presente nella scansione precedente non è più inviato dal server.',
          evidence: 'Header Strict-Transport-Security assente nei nuovi header di risposta.',
          confidence: 0.95,
          technicalEvidence: {
            host: 'shop.fashion-global.com',
            port: 443,
            engine: 'HTTP Header Security Auditor',
            rawEvidence: 'HTTP/2 200 OK\nserver: nginx/1.24.0\ncontent-type: text/html\n(strict-transport-security missing)',
            confidencePercentage: 95,
            firstSeen: '2026-08-27 18:30:00 UTC',
            lastVerified: '2026-08-27 20:15:00 UTC',
          },
        },
        {
          id: 'avail-ttfb-degraded',
          category: 'availability',
          severity: 'medium',
          status: 'open',
          title: 'Degradamento Latenza TTFB (680ms)',
          description: 'Il tempo di risposta del server è aumentato di 490ms rispetto alla baseline (190ms -> 680ms).',
          evidence: 'TTFB misurato: 680ms (Soglia accettabile: < 250ms)',
          confidence: 0.92,
          technicalEvidence: {
            host: 'shop.fashion-global.com',
            engine: 'Waterfall TTFB Probe (Edge Socket)',
            rawEvidence: 'DNS Lookup: 18ms\nTCP Handshake: 32ms\nTLS Negotiation: 45ms\nServer Processing (TTFB): 680ms\nTotal Transaction: 775ms',
            confidencePercentage: 92,
            firstSeen: '2026-08-27 18:30:00 UTC',
            lastVerified: '2026-08-27 20:15:00 UTC',
          },
        },
      ],
      deductions: [
        {
          findingId: 'sec-port-exposed-6379',
          rule: 'Porta Critica Esposta: 6379 (Redis)',
          points: 35,
          reason: 'Esposizione diretta Redis su IP pubblico.',
          severity: 'critical',
        },
        {
          findingId: 'sec-file-env-exposed',
          rule: 'File .env Esposto',
          points: 35,
          reason: 'File di configurazione contenente credenziali scaricabile.',
          severity: 'critical',
        },
        {
          findingId: 'sec-hsts-removed',
          rule: 'Header HSTS Rimosso',
          points: 20,
          reason: 'Regressione configurazione di sicurezza HTTPS.',
          severity: 'high',
        },
        {
          findingId: 'avail-ttfb-degraded',
          rule: 'Degradamento TTFB',
          points: 10,
          reason: 'Latenza di elaborazione server > 600ms.',
          severity: 'medium',
        },
      ],
    },
    previousAssessment: {
      overallScore: 95,
      grade: 'A',
      summary: 'Postura precedente eccellente prima della release applicativa #148.',
      breakdown: {
        exposureScore: 98,
        postureScore: 95,
        operationalScore: 92,
        formulaExplanation: 'Punteggio Finale (95) = Exposure [98] × 50% + Posture [95] × 30% + Operational [92] × 20%',
      },
      pillars: {
        availability: { category: 'availability', score: 92, criticalCount: 0, highCount: 0, mediumCount: 0, lowCount: 0, infoCount: 2 },
        configuration: { category: 'configuration', score: 95, criticalCount: 0, highCount: 0, mediumCount: 0, lowCount: 1, infoCount: 3 },
        security: { category: 'security', score: 98, criticalCount: 0, highCount: 0, mediumCount: 0, lowCount: 0, infoCount: 4 },
      },
      findings: [],
      deductions: [],
    },
    diffResult: {
      target: 'shop.fashion-global.com',
      previousTimestamp: new Date(Date.now() - 86400000).toISOString(),
      currentTimestamp: new Date().toISOString(),
      previousScore: 95,
      currentScore: 28,
      scoreDelta: -67,
      previousGrade: 'A',
      currentGrade: 'F',
      changes: [
        {
          id: 'drift-port-6379',
          category: 'security',
          changeType: 'added',
          title: 'NUOVA PORTA CRITICA APERTA: 6379 (Redis In-Memory Cache)',
          previousEvidence: 'Porta 6379 CHIUSA / Filtrata',
          currentEvidence: 'Socket TCP 6379 aperto su IP pubblico 198.51.100.42 (connessione accettata)',
          severity: 'critical',
          description: 'La porta Redis è stata esposta pubblicamente su internet a seguito di una modifica errata alle regole firewall durante il deploy #148.',
          technicalEvidence: {
            host: 'shop.fashion-global.com',
            port: 6379,
            engine: 'Port Scanner Pro',
            rawEvidence: 'Socket 6379/TCP OPEN (+PONG)',
            confidencePercentage: 99,
            firstSeen: '2026-08-27 18:30:00 UTC',
            lastVerified: '2026-08-27 20:15:00 UTC',
          },
        },
        {
          id: 'drift-file-env',
          category: 'security',
          changeType: 'added',
          title: 'NUOVO FILE SENSIBILE ESPOSTO: /.env',
          previousEvidence: 'HTTP 404 Not Found',
          currentEvidence: 'HTTP 200 OK con testo contenente DB_PASSWORD e JWT_SECRET',
          severity: 'critical',
          description: 'Un file .env contenente credenziali del database e chiavi Stripe è stato accidentalmente copiato nella web root durante la build.',
          technicalEvidence: {
            host: 'shop.fashion-global.com',
            engine: 'Sensitive File Leak Scanner',
            rawEvidence: 'HTTP/1.1 200 OK\nContent-Type: text/plain\nLength: 1420 bytes',
            confidencePercentage: 98,
            firstSeen: '2026-08-27 18:30:00 UTC',
            lastVerified: '2026-08-27 20:15:00 UTC',
          },
        },
        {
          id: 'drift-hsts-removed',
          category: 'configuration',
          changeType: 'degraded',
          title: 'HEADER DI SICUREZZA RIMOSSO: HSTS',
          previousEvidence: 'Strict-Transport-Security: max-age=31536000; includeSubDomains',
          currentEvidence: 'Header non presente nella risposta HTTP',
          severity: 'high',
          description: 'L’header Strict-Transport-Security è stato eliminato dalla configurazione del web server Nginx.',
        },
        {
          id: 'drift-ttfb-degraded',
          category: 'availability',
          changeType: 'degraded',
          title: 'DEGRADO SEVERO LATENZA SERVER (TTFB: 680ms)',
          previousEvidence: '190 ms (Ottimale)',
          currentEvidence: '680 ms (+490 ms di regressione)',
          severity: 'medium',
          description: 'Il tempo di elaborazione server è aumentato a causa del sovraccarico o della misconfigurazione del caching edge.',
        },
      ],
      timeline: [
        {
          id: 'evt-1',
          date: '27 Agosto 2026 - 18:30',
          title: 'Nuova porta critica 6379 aperta (Redis)',
          category: 'security',
          classification: 'new',
          description: 'Rilevata connessione TCP aperta su interfaccia pubblica.',
          severity: 'critical',
          evidence: '198.51.100.42:6379 OPEN',
        },
        {
          id: 'evt-2',
          date: '27 Agosto 2026 - 18:30',
          title: 'File /.env esposto pubblicamente',
          category: 'security',
          classification: 'new',
          description: 'HTTP 200 OK rilevato su file di configurazione.',
          severity: 'critical',
          evidence: 'GET /.env -> 200 OK',
        },
        {
          id: 'evt-3',
          date: '27 Agosto 2026 - 18:30',
          title: 'Header HSTS rimosso',
          category: 'configuration',
          classification: 'modified',
          description: 'Direttiva Strict-Transport-Security assente rispetto al giorno precedente.',
          severity: 'high',
          evidence: 'Header mancante',
        },
        {
          id: 'evt-4',
          date: '26 Agosto 2026 - 10:00',
          title: 'Certificato SSL rinnovato con successo',
          category: 'configuration',
          classification: 'resolved',
          description: 'Certificato emesso da DigiCert con validità estesa a 12 mesi.',
          severity: 'info',
          evidence: 'Validità: 365 giorni',
        },
        {
          id: 'evt-5',
          date: '20 Agosto 2026 - 14:00',
          title: 'Nuovo sottodominio rilevato: cdn.fashion-global.com',
          category: 'availability',
          classification: 'new',
          description: 'Discovery DNS ha individuato un nuovo record CNAME puntato ad AWS CloudFront.',
          severity: 'info',
          evidence: 'CNAME d1234.cloudfront.net',
        },
      ],
      summary: {
        newVulnerabilities: 2,
        resolvedVulnerabilities: 0,
        configDrifts: 2,
        latencyDeltaMs: 490,
      },
    },
    rawResults: {
      target: 'shop.fashion-global.com',
      ttfb: { ttfb: 680 },
      ports: { openPorts: [80, 443, 6379, 8080] },
      files: [{ exposed: true, path: '/.env', status: 200, size: 1420 }],
    },
  },

  staging_k8s: {
    id: 'staging_k8s',
    name: 'Staging Kubernetes Cluster (Stage)',
    badge: 'Certificato in Scadenza (3 gg) • Grado C',
    tagline: 'Ambiente di collaudo con certificato SSL Let’s Encrypt in scadenza e policy email permissiva.',
    asset: {
      id: 'asset-stage-03',
      name: 'K8s Staging Ingress',
      target: 'k8s-stage.internal-dev.net',
      environment: 'staging',
      criticality: 'medium',
      owner: 'QA & Backend Team (qa-team@internal-dev.net)',
      tags: ['Staging', 'Kubernetes', 'Testing'],
      notes: 'Cluster di pre-rilascio per test funzionali.',
      created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
      last_scan_score: 64,
      last_scan_grade: 'C',
      last_scan_at: new Date().toISOString(),
    },
    assessment: {
      overallScore: 64,
      grade: 'C',
      summary: 'Postura di staging discreta: punteggio 64/100 (Grado C). Richiesto rinnovo certificato SSL e revisione porta SSH esposta.',
      breakdown: {
        exposureScore: 70,
        postureScore: 50,
        operationalScore: 85,
        formulaExplanation: 'Punteggio Finale (64) = Exposure [70] × 50% + Posture [50] × 30% + Operational [85] × 20%',
      },
      pillars: {
        availability: { category: 'availability', score: 85, criticalCount: 0, highCount: 0, mediumCount: 0, lowCount: 1, infoCount: 2 },
        configuration: { category: 'configuration', score: 50, criticalCount: 0, highCount: 1, mediumCount: 1, lowCount: 0, infoCount: 1 },
        security: { category: 'security', score: 70, criticalCount: 0, highCount: 0, mediumCount: 1, lowCount: 1, infoCount: 2 },
      },
      findings: [
        {
          id: 'sec-ssl-expiry',
          category: 'configuration',
          severity: 'high',
          status: 'open',
          title: 'Certificato SSL/TLS in Scadenza (3 giorni)',
          description: 'Il certificato crittografico scadrà tra 3 giorni; se non rinnovato, i browser bloccheranno gli accessi con allarme di sicurezza.',
          evidence: 'Valido fino al: 30 Agosto 2026 (Giorni rimanenti: 3)',
          impact: 'Possibile interruzione totale dell’ambiente di staging per blocco HSTS e alert nei browser.',
          confidence: 0.99,
          technicalEvidence: {
            host: 'k8s-stage.internal-dev.net',
            port: 443,
            engine: 'SSL/TLS Certificate Verifier',
            rawEvidence: 'Subject: CN=k8s-stage.internal-dev.net\nIssuer: Let\'s Encrypt Authority X3\nValid from: 2026-06-01\nValid to: 2026-08-30 (3 days left)',
            confidencePercentage: 100,
            firstSeen: '2026-08-20 08:00:00 UTC',
            lastVerified: '2026-08-27 20:00:00 UTC',
          },
          remediation: {
            action: 'Verificare il funzionamento del pod cert-manager in Kubernetes ed eseguire il rinnovo ACME.',
            codeSnippet: 'kubectl get certificaterequests -n ingress-nginx\ncmctl renew staging-ingress-cert',
            structured: {
              problem: 'Certificato SSL/TLS Let’s Encrypt a 3 giorni dalla scadenza.',
              risk: 'Disruption dell’ambiente di collaudo con errore SSL_ERROR_BAD_CERT_DOMAIN nei client.',
              immediateActions: [
                '1. Controllare i log di cert-manager: `kubectl logs -n cert-manager deploy/cert-manager`.',
                '2. Forzare il rinnovo: `cmctl renew staging-ingress-cert -n ingress-nginx`.',
                '3. Verificare che la Challenge HTTP-01 o DNS-01 vada a buon fine.',
              ],
              verification: 'Eseguire `echo | openssl s_client -connect k8s-stage.internal-dev.net:443 2>/dev/null | openssl x509 -noout -dates` e verificare la nuova data di scadenza.',
            },
          },
        },
        {
          id: 'sec-dmarc-weak',
          category: 'configuration',
          severity: 'medium',
          status: 'open',
          title: 'Policy DMARC in Modalità Monitoraggio (p=none)',
          description: 'Il record DMARC è impostato su p=none, non bloccando le email contraffatte.',
          evidence: 'v=DMARC1; p=none; sp=none; rua=mailto:dmarc@internal-dev.net',
          confidence: 0.95,
          technicalEvidence: {
            host: 'k8s-stage.internal-dev.net',
            engine: 'DNS TXT & SPF/DKIM/DMARC Auditor',
            rawEvidence: '_dmarc.internal-dev.net TXT "v=DMARC1; p=none; sp=none; rua=mailto:dmarc@internal-dev.net"',
            confidencePercentage: 95,
            firstSeen: '2026-08-10 09:00:00 UTC',
            lastVerified: '2026-08-27 20:00:00 UTC',
          },
        },
        {
          id: 'sec-port-ssh-exposed',
          category: 'security',
          severity: 'medium',
          status: 'open',
          title: 'Porta SSH 22 Esposta Pubblicamente',
          description: 'La porta di amministrazione SSH del nodo master è aperta su internet.',
          evidence: 'Socket TCP 22 aperto su IP pubblico.',
          confidence: 0.95,
          technicalEvidence: {
            host: 'k8s-stage.internal-dev.net',
            port: 22,
            engine: 'Port Scanner Pro',
            rawEvidence: 'Port 22/TCP OPEN (OpenSSH_8.9p1 Ubuntu-3ubuntu0.6)',
            confidencePercentage: 95,
            firstSeen: '2026-08-01 10:00:00 UTC',
            lastVerified: '2026-08-27 20:00:00 UTC',
          },
          remediation: {
            action: 'Limitare l’accesso SSH alla sola VPN aziendale o IP dell’ufficio.',
            codeSnippet: 'sudo ufw delete allow 22/tcp\nsudo ufw allow from 10.8.0.0/24 to any port 22 proto tcp',
            structured: {
              problem: 'Porta SSH 22/TCP esposta direttamente su IP pubblico senza restrizione di rete.',
              risk: 'Attacchi di forza bruta e tentativi di accesso non autorizzato al nodo master.',
              immediateActions: [
                '1. Limitare l’accesso SSH nel Security Group o con UFW solo alla subnet VPN `10.8.0.0/24`.',
                '2. Disabilitare autenticazione via password in `/etc/ssh/sshd_config`.',
              ],
              verification: 'Eseguire connessione SSH da un IP esterno e confermare il timeout o blocco firewall.',
            },
          },
        },
      ],
      deductions: [
        { findingId: 'sec-ssl-expiry', rule: 'Certificato SSL in Scadenza', points: 15, reason: 'Scadenza imminente (3 giorni)', severity: 'high' },
        { findingId: 'sec-dmarc-weak', rule: 'Policy DMARC Debole', points: 7, reason: 'Policy p=none', severity: 'medium' },
        { findingId: 'sec-port-ssh-exposed', rule: 'Porta SSH 22 Esposta', points: 7, reason: 'Gestione remota accessibile da internet', severity: 'medium' },
      ],
    },
    rawResults: {
      target: 'k8s-stage.internal-dev.net',
      ssl: { valid: true, daysRemaining: 3, issuer: "Let's Encrypt Authority X3" },
      ports: { openPorts: [22, 80, 443] },
    },
  },
};

