'use client';

import { useState } from 'react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { TestResult, TestStatus } from '@/types/tests';

export function useSecurityAudit() {
  const [results, setResults] = useState<Record<string, TestResult | null>>({
    spf: null,
    dkim: null,
    dmarc: null,
    dnssec: null,
    headers: null,
    tls: null,
    admin: null,
    subdomains: null,
    blacklist: null,
    ports: null,
  });
  const [loading, setLoading] = useState<Record<string, boolean>>({});
  const [overallScore, setOverallScore] = useState<number | null>(null);

  const updateResult = (id: string, update: Partial<TestResult>) => {
    setResults(prev => {
      const current = prev[id] || { id, name: id, status: 'idle', timestamp: Date.now() };
      return { ...prev, [id]: { ...current, ...update, timestamp: Date.now() } as TestResult };
    });
  };

  const calculateScore = (currentResults: Record<string, TestResult | null>) => {
    let score = 100;
    Object.values(currentResults).forEach(res => {
      if (!res) return;
      if (res.status === 'fail') score -= 15;
      if (res.status === 'warning') score -= 5;
    });
    return Math.max(0, score);
  };

  const runTest = async (id: string, endpoint: string, target: string) => {
    const cleanTarget = (target || '').replace(/^https?:\/\//, '').replace(/\/.*$/, '').trim();
    setLoading(prev => ({ ...prev, [id]: true }));
    updateResult(id, { status: 'running' });

    try {
      const targetEndpoints = ['headers', 'ports', 'admin'];
      const param = targetEndpoints.includes(endpoint) ? 'target' : 'domain';
      const res = await fetch(`/api/security/${endpoint}?${param}=${cleanTarget}`);
      const data = await res.json();

      if (res.ok) {
        updateResult(id, {
          status: data.status as TestStatus,
          result: data,
          error: undefined
        });
      } else {
        updateResult(id, { status: 'fail', error: data.error });
      }
    } catch {
      updateResult(id, { status: 'fail', error: 'Test fallito' });
    } finally {
      setLoading(prev => ({ ...prev, [id]: false }));
    }
  };

  const runAll = async (target: string) => {
    const tests = [
      { id: 'spf', endpoint: 'spf' },
      { id: 'dkim', endpoint: 'dkim' },
      { id: 'dmarc', endpoint: 'dmarc' },
      { id: 'dnssec', endpoint: 'dnssec' },
      { id: 'headers', endpoint: 'headers' },
      { id: 'tls', endpoint: 'tls' },
      { id: 'admin', endpoint: 'admin' },
      { id: 'subdomains', endpoint: 'subdomains' },
      { id: 'blacklist', endpoint: 'blacklist' },
      { id: 'ports', endpoint: 'ports' },
    ];

    for (const test of tests) {
      await runTest(test.id, test.endpoint, target);
    }

    setResults(prev => {
      setOverallScore(calculateScore(prev));
      return prev;
    });
  };

  const generatePDF = (domain: string) => {
    const doc = new jsPDF();
    const date = new Date().toLocaleString();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(37, 99, 235); // Blue
    doc.text('Security Audit Report', 14, 22);
    
    doc.setFontSize(12);
    doc.setTextColor(100, 116, 139); // Slate
    doc.text(`Domain: ${domain}`, 14, 32);
    doc.text(`Date: ${date}`, 14, 38);
    doc.text(`Security Score: ${overallScore}/100`, 14, 44);

    const tableData = Object.entries(results)
      .filter(([, res]) => res !== null)
      .map(([key, res]) => {
        const securityRes = res!.result as { message?: string; recommendation?: string };
        return [
          key.toUpperCase(),
          res!.status.toUpperCase(),
          securityRes.message || 'N/A',
          securityRes.recommendation || 'N/A'
        ];
      });

    autoTable(doc, {
      startY: 55,
      head: [['Test', 'Status', 'Findings', 'Remediation']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [30, 41, 59] },
    });

    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text('Generated by NetworkDiag', 14, doc.internal.pageSize.height - 10);

    doc.save(`security-audit-${domain}-${Date.now()}.pdf`);
  };

  return { results, loading, overallScore, runAll, generatePDF };
}
